services:
  yyb-go:
    image: ghcr.io/melon0826/yyb:latest
    container_name: yyb-go
    restart: unless-stopped
    ports:
      - "8181:8181"
    environment:
      - YYB_USERNAME=melon0826
      - YYB_PASSWORD=826523lgho
      - YYB_PORT=8181
    volumes:
      - yyb-data:/app/resource/db

volumes:
  yyb-data:
